export default {
  emptyName: 'Please enter name.',
  invalidName: 'Please enter valid name.',
  emptyFullName: 'Please enter full name.',
  invalidFullName: 'Please enter valid full name.',
  emptyUserName: 'Please enter user name.',
  invalidUserName: 'Please enter a valid user name.',
  emptyBio: 'Please enter bio.',
  invalidBio: 'Please enter a valid bio.',
  emptyLinks: 'Please enter link.',
  invalidLinks: 'Please enter a valid link.',
  emptySurname: 'Please enter surname.',
  passwordMismatch: 'Password and confirm password does not match.',
  oldPassword: 'Please enter old password',
  newPassword: 'Please enter new password',
  reEnterNewPassword: 'Please enter confirm password',
  invalidSurname: 'Please enter valid surname.',
  emptypostalAdreess: 'Please enter postal address. ',
  invalidpostalAdreess: 'Please enter valid postal address.',
  emptyMobile: 'Please enter mobile number',
  invalidMobile: 'Please enter valid mobile number',
  emptyEmail: 'Please enter email',
  userName: 'Please enter email/username.',
  invalidEmail: 'Please enter valid email',
  emptyPassword: 'Please enter password',
  invalidPassword: 'Please enter strong password (Ex.Jhon@123).',
  emptyConfirmPassword: 'Please enter confirm password',
  invalidConfirmPassword:
    'Password must contain one uppercase, one lowercase and one number',
  emptyAnnouce: 'Please enter title of your annouce.',
  invalidAnnouce: 'Please enter valid title of your annouce.',
  emptyremark: 'Please enter remark.',
  invalidRemark: 'Please enter valid remark',
  emptyactiveBoxError: 'Please select legal notice and terms of used.',
  emptyDescription: 'Please enter description.',
  emptyPrice: 'Please enter price.',
  passwordNotMatch: 'Password does not match with confirm password.',
  emtyDistance: 'Please select distance.',
  emptyOtp: 'Please enter otp.',
  invalidOtp: 'Please enter valid otp.',
  emptyIBAN: `Please enter iban.`,
  invalidIBAN: `Please enter valid iban.`,
  emptyPostalcode: `Please enter postalcode.`,
  invalidPostalcode: `Please enter valid postalcode.`,
  emptyCity: `Please enter city.`,
  invalidCity: `Please enter valid city.`,
  emptyOwnerName: 'Please enter owner name.',
  invalidOwnerName: 'Please enter valid owner name.',
  emptyBillingAdreess: 'Please enter billing address. ',
  invalidBillingAddress: 'Please enter valid billing address.',
  emptySpecialPrecaution: 'Please enter specialprecaution.',
  emptyWeekendPrice: 'Please enter weekend price.',
  emptyPriceperweek: 'Please enter price per week.',
  emptyPhoneNumber: 'Please enter phone number & country code',
  invalidPhoneNumber: 'Please enter valid phone number.',
  emptyLocation: 'Please enter location',
  invalidLocation: 'Please enter valid  location',
  emptyDeliveryCost: 'Please Delivery cost.',
  emptyReportMessage: 'Please enter message',
  emptyChatRenterMessage: 'Please enter message',
  invalidPostalAddress: 'Please enter valid postal address',
  emptyOfferPrice: 'Please enter price',
  emptyMessage: 'Please enter message.',
  invalidMessage: 'Please enter valid message.',
};
